### ISSUE TITLE
mm10 build?

### ISSUE THREAD

**Issue by holgerbrandl** [wassermanlab/JASPAR-UCSC-tracks#6]
It would be great if you could also provide tfbs prediction tracks for mm10

**Comment by robinvanderlee** [comment]
Mouse mm10 predictions, made with version 1.0 of the `JASPAR-UCSC-tracks` code (i.e. using `MEME` and `bioperl`, rather than `PWMScan`) are available through the UCSC browser JASPAR track hub. More information on [http://jaspar.genereg.net/genome-tracks/#ucsc_tracks](http://jaspar.genereg.net/genome-tracks/#ucsc_tracks). The underlying data can be downloaded at [http://expdata.cmmt.ubc.ca/JASPAR/downloads/UCSC_tracks/2018/](http://expdata.cmmt.ubc.ca/JASPAR/downloads/UCSC_tracks/2018/). Updates on which genome tracks are available will follow for the next version of JASPAR, but users can continue to make requests.

**Comment by holgerbrandl** [comment]
Thanks for the quick help and for providing this great resource.

To make mouse more accessible, you could potentially update the "direct links" section on http://jaspar.genereg.net/genome-tracks/#ucsc_tracks since it seems to include all species from the track-hub except  mouse and zebrafish.
